USE [master]
GO

/****** Object:  Database [dbbooks]    Script Date: 4/23/2017 2:54:57 PM ******/
CREATE DATABASE [dbbooks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbbooks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\dbbooks.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dbbooks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\dbbooks_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dbbooks] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbbooks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbbooks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbbooks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbbooks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbbooks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbbooks] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbbooks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbbooks] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dbbooks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbbooks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbbooks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbbooks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbbooks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbbooks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbbooks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbbooks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbbooks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbbooks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbbooks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbbooks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbbooks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbbooks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbbooks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbbooks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbbooks] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dbbooks] SET  MULTI_USER 
GO

ALTER DATABASE [dbbooks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbbooks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbbooks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbbooks] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dbbooks] SET  READ_WRITE 
GO

